### Update request to patient-controller
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe@example.com",
  "address": "123 this street",
  "dateOfBirth": "1995-05-05"
}

###